engine:
  type: "in_memory"
network:
  address: ":7777"
  max_connections: 100
  max_message_size: "4KB"
  idle_timeout: 5m
logging:
  level: "info"
  output: "./goVault/log/output.log"
  stdout: true
wal:
  flushing_batch_length: 100
  flushing_batch_timeout: "10ms"
  max_segment_size: "10MB"
  data_directory: "./goVault/data/wal"