version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:7777"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./docker/log/:/goVault/log/
      - ./docker/data/:/goVault/data/
    environment:
      - CONFIG_PATH=/app/config.yaml