// Code generated by MockGen. DO NOT EDIT.
// Source: goVault/internal/network (interfaces: TCPServer)
//
// Generated by this command:
//
//	mockgen -destination ./../../mocks/network/contract.go -package network_mock . TCPServer
//

// Package network_mock is a generated GoMock package.
package network_mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTCPServer is a mock of TCPServer interface.
type MockTCPServer struct {
	ctrl     *gomock.Controller
	recorder *MockTCPServerMockRecorder
	isgomock struct{}
}

// MockTCPServerMockRecorder is the mock recorder for MockTCPServer.
type MockTCPServerMockRecorder struct {
	mock *MockTCPServer
}

// NewMockTCPServer creates a new mock instance.
func NewMockTCPServer(ctrl *gomock.Controller) *MockTCPServer {
	mock := &MockTCPServer{ctrl: ctrl}
	mock.recorder = &MockTCPServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTCPServer) EXPECT() *MockTCPServerMockRecorder {
	return m.recorder
}

// HandleQueries mocks base method.
func (m *MockTCPServer) HandleQueries(ctx context.Context, handler func(context.Context, []byte) []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleQueries", ctx, handler)
}

// HandleQueries indicates an expected call of HandleQueries.
func (mr *MockTCPServerMockRecorder) HandleQueries(ctx, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleQueries", reflect.TypeOf((*MockTCPServer)(nil).HandleQueries), ctx, handler)
}
