// Code generated by MockGen. DO NOT EDIT.
// Source: goVault/internal/core/query (interfaces: Parser)
//
// Generated by this command:
//
//	mockgen -destination ./../../../mocks/core/query/contract.go -package query_mock . Parser
//

// Package query_mock is a generated GoMock package.
package query_mock

import (
	query "goVault/internal/core/query"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockParser is a mock of Parser interface.
type MockParser struct {
	ctrl     *gomock.Controller
	recorder *MockParserMockRecorder
}

// MockParserMockRecorder is the mock recorder for MockParser.
type MockParserMockRecorder struct {
	mock *MockParser
}

// NewMockParser creates a new mock instance.
func NewMockParser(ctrl *gomock.Controller) *MockParser {
	mock := &MockParser{ctrl: ctrl}
	mock.recorder = &MockParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParser) EXPECT() *MockParserMockRecorder {
	return m.recorder
}

// Transition mocks base method.
func (m *MockParser) Transition(arg0 string) (*query.Query, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transition", arg0)
	ret0, _ := ret[0].(*query.Query)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transition indicates an expected call of Transition.
func (mr *MockParserMockRecorder) Transition(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transition", reflect.TypeOf((*MockParser)(nil).Transition), arg0)
}
