name: Fmt

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  format:
    name: Check Go Code Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Check formatting
        run: gofmt -l -s .
